#!/usr/bin/env python3
"""Build the public submission repo: code, data and the policy, nothing else.

    tools/make_public.py [--out ../GhostTrial-public] [--commit]

This repo is the working archive -- 8 GB of history, 3.6 GB of Pit render frames,
and third-party video that is fine to hold on disk and wrong to publish. The
hackathon wants a GitHub link, so this copies out a clean tree with its own
history: the pipeline, the motion data derived from our own commissioned capture,
the training config, and the exported policy.

What it takes: every git-tracked file, minus the EXCLUDE rules below. Tracked is
the safe base -- anything already gitignored (the MK footage, the shoot, the
soundtrack, the reports, the renders) cannot leak through by accident.

Writes a manifest to <out>/docs/PUBLISHED.md so the two trees can be compared
later without re-deriving any of this.
"""
import argparse
import re
import shutil
import subprocess
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

# (glob or prefix, why it stays behind) -- the reasons are published too
EXCLUDE = [
    ("presentation/", "the video and everything staged for it: MK stills, the "
                      "soundtrack, 3.6 GB of Pit frames, BlenderKit scene assets"),
    ("raw/mixamo/*.fbx", "Mixamo assets are free to use but not to redistribute; "
                         "raw/mixamo/README.md says which clips and how to fetch them"),
    ("raw/mixamo/bvh/", "converted straight from those Mixamo FBX, so the same terms"),
    ("data/gemx_output/*/preprocess/", "per-frame ViT features, boxes and camera "
                                       "solved straight off the performer's video"),
    ("a5n.csv", "scratch file, no longer referenced"),
    ("tools/submission_report.py", "the internal submission checklist: local paths, "
                                   "account and token layout, nothing a reader needs"),
]

# extra files, copied in from outside the tracked tree: dest -> source
EXTRA = {
    "policy/model_step_003750_g1.onnx":
        "logs_rl/nebius_t12/exported/model_step_003750_g1.onnx",
    "policy/model_step_003750_encoder.onnx":
        "logs_rl/nebius_t12/exported/model_step_003750_encoder.onnx",
    "policy/model_step_003750_decoder.onnx":
        "logs_rl/nebius_t12/exported/model_step_003750_decoder.onnx",
    "policy/README.md": "docs/model_card.md",   # doubles as the HF model card
    "policy/config.yaml": "logs_rl/nebius_t12/config.yaml",
    "policy/model_config.yaml": "logs_rl/nebius_t12/model_config.yaml",
}


def tracked():
    out = subprocess.run(["git", "ls-files"], cwd=REPO, capture_output=True,
                         text=True, check=True).stdout
    return [p for p in out.splitlines() if p]


def excluded(path: str):
    for rule, why in EXCLUDE:
        if "*" in rule:
            if re.search(rule.replace("*", "[^/]*"), path):
                return rule, why
        elif path == rule or path.startswith(rule):
            return rule, why
    return None


def human(n):
    for unit in ("B", "KB", "MB", "GB"):
        if n < 1024 or unit == "GB":
            return f"{n:.0f} {unit}" if unit == "B" else f"{n:.1f} {unit}"
        n /= 1024


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=str(REPO.parent / "GhostTrial-public"))
    ap.add_argument("--commit", action="store_true",
                    help="git init and commit the result")
    args = ap.parse_args()
    out = Path(args.out).resolve()

    kept, dropped = [], {}
    for path in tracked():
        hit = excluded(path)
        if hit:
            dropped.setdefault(hit, []).append(path)
        else:
            kept.append(path)

    if out.exists():
        for child in out.iterdir():
            if child.name != ".git":
                shutil.rmtree(child) if child.is_dir() else child.unlink()
    out.mkdir(parents=True, exist_ok=True)

    total = 0
    for path in kept:
        src, dst = REPO / path, out / path
        if not src.exists():
            continue
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dst)
        total += dst.stat().st_size

    extras = []
    for dest, source in EXTRA.items():
        src = REPO / source
        if not src.exists():
            print(f"  missing, not copied: {source}")
            continue
        dst = out / dest
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dst)
        extras.append((dest, dst.stat().st_size))
        total += dst.stat().st_size

    # the manifest: what went, what stayed, and why
    lines = ["# What is published here, and what is not", "",
             f"Generated by `tools/make_public.py` from the working repo.",
             "", f"**{len(kept) + len(extras)} files, {human(total)}.**", "",
             "## Included", ""]
    by_dir = {}
    for path in kept:
        by_dir.setdefault(str(Path(path).parent).split("/")[0] or ".", []).append(path)
    lines += ["| area | files | what it is |", "|---|---|---|"]
    WHAT = {
        "data": "motion data: the capture solved to human BVH, retargeted to G1, "
                "frozen CSV takes and the motion_lib pickles SONIC trains on",
        "tools": "the pipeline, end to end: retarget, retime, balance, feasibility "
                 "checks, figures, training and eval jobs",
        "docs": "methodology: the capture brief, the video-to-pose plan, the "
                "training environment",
        "docker": "the Isaac Lab image the training and export run in",
        "raw": "the one clip authored by hand, plus READMEs pointing at sources "
               "held back",
        ".": "README and .gitignore",
    }
    for key in sorted(by_dir):
        lines.append(f"| `{key}` | {len(by_dir[key])} | {WHAT.get(key, '')} |")
    if extras:
        lines.append(f"| `policy` | {len(extras)} | the fine-tuned SONIC policy "
                     f"exported to ONNX, with the config it trained under |")
    lines += ["", "## Held back", "",
              "| what | files | why |", "|---|---|---|"]
    for (rule, why), paths in sorted(dropped.items()):
        lines.append(f"| `{rule}` | {len(paths)} | {why} |")
    lines += ["",
              "Also never tracked in the first place, so absent from both trees: the "
              "1992 behind-the-scenes footage, the commissioned capture and every "
              "frame cut from it, the soundtrack, the Nebius and Mixamo screen "
              "recordings, the reports, and the training checkpoints.", ""]
    (out / "docs").mkdir(parents=True, exist_ok=True)
    (out / "docs" / "PUBLISHED.md").write_text("\n".join(lines))

    print(f"{out}")
    print(f"  {len(kept)} tracked files + {len(extras)} extras, {human(total)}")
    for (rule, _), paths in sorted(dropped.items()):
        print(f"  held back: {rule:34s} {len(paths)} file(s)")

    if args.commit:
        if not (out / ".git").exists():
            subprocess.run(["git", "init", "-q", "-b", "main"], cwd=out, check=True)
        subprocess.run(["git", "add", "-A"], cwd=out, check=True)
        subprocess.run(["git", "commit", "-q", "-m",
                        "GhostTrial: Scorpion spear throw and uppercut on a Unitree G1"],
                       cwd=out, check=False)
        print("  committed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
