#!/usr/bin/env python3
"""Two rc-doc pages for shipping this entry.

    tools/submission_report.py

    reports/publication.html   what goes to GitHub and what stays here, generated
                               from the same rules tools/make_public.py applies
    reports/submission.html    the checklist to follow on the day, in order

The publication page is generated rather than written so it cannot drift from the
tree that is actually published: the file counts, sizes and exclusion reasons all
come out of make_public.

Styling and the nav strip are borrowed from the sibling reports at generation
time, the same way presentation/levels_report.py does it.
"""
import html
import re
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent
REPORTS = REPO / "reports"
PUBLIC = REPO.parent / "GhostTrial-public"
DATE = "2026-08-15"
DEADLINE = "Sun 16 Aug 2026, 11:59pm PT"
FORM = "https://account.ultimatebots.com/ghost-trial?linked=github"

sys.path.insert(0, str(HERE))
import make_public  # noqa: E402


def esc(t):
    return html.escape(str(t), quote=False)


def borrowed_style():
    for src in sorted(REPORTS.glob("0*.html")):
        blocks = re.findall(r"<style>.*?</style>", src.read_text(), flags=re.S)
        if blocks:
            return "\n".join(blocks)
    return "<style>body{background:#0f1216;color:#e7edf3;font-family:sans-serif}</style>"


def nav(here):
    out = ['<a href="index.html">&#9666; index</a>']
    for f in sorted(REPORTS.glob("[0-9][0-9]-*.html")):
        m = re.search(r"<h1>(.*?)</h1>", f.read_text(), flags=re.S)
        title = re.sub(r"<[^>]+>", "", m.group(1)).strip() if m else f.stem
        out.append(f'<a href="{f.name}">{esc(title)}</a>')
    for name, label in (("submission.html", "Submitting &mdash; the checklist"),
                        ("publication.html", "What is published")):
        cls = ' class="here"' if name == here else ""
        out.append(f'<a href="{name}"{cls}>{label}</a>')
    return f'<div class="rnav">{"".join(out)}</div>'


def page(name, title, lead, body):
    return f'''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="rc-date" content="{DATE}">
<title>Ghost Trial 03 · {esc(title)}</title>
{borrowed_style()}
</head>
<body>
<div class="wrap">{nav(name)}
<h1>{esc(title)}</h1>
<p class="rlead">{lead}</p>
{body}
<p class="foot">Generated by <code>tools/submission_report.py</code>.</p>
</div></body></html>
'''


def survey():
    """Run make_public's rules over the tracked tree without copying anything."""
    kept, dropped = [], {}
    for path in make_public.tracked():
        hit = make_public.excluded(path)
        (dropped.setdefault(hit, []).append(path) if hit else kept.append(path))
    sizes = {}
    for path in kept:
        f = REPO / path
        sizes[path] = f.stat().st_size if f.exists() else 0
    return kept, dropped, sizes


def du(path: Path):
    if not path.exists():
        return "not built"
    out = subprocess.run(["du", "-sh", "--exclude=.git", str(path)],
                         capture_output=True, text=True).stdout
    return out.split()[0] if out else "?"


# --------------------------------------------------------------------------- #

AREA = {
    "data": "The motion itself: the capture solved to a human skeleton, hand-corrected, "
            "retargeted to the G1, retimed, frozen as CSV takes, and converted to the "
            "motion_lib pickles SONIC trains on. This is the dataset the entry is judged on.",
    "tools": "The pipeline end to end — retarget, retime, balance, contact and dynamic "
             "feasibility, the Nebius jobs, the ONNX export, and the figure scripts.",
    "docs": "Methodology: the capture brief as it was posted, the video-to-pose plan, the "
            "training environment, and the submission summary.",
    "docker": "The Isaac Lab image that training, rollout and export all run inside.",
    "raw": "The one clip authored by hand, and READMEs naming the sources that are not here.",
    ".": "README and .gitignore.",
    "policy": "The fine-tuned policy exported to ONNX, with the config it trained under.",
}

NEVER = [
    ("The 1992 behind-the-scenes footage", "raw/mk-bts-*",
     "Warner Bros./NetherRealm. Style reference only — it never entered training. "
     "The READMEs stay so the provenance is on the record."),
    ("The commissioned capture", "raw/capture-01, raw/capture-02, data/sync_media",
     "Video of a real person, filmed for this project. The motion derived from it is "
     "published; the footage and every frame cut from it is not."),
    ("The soundtrack and its session", "presentation/music",
     "Commissioned audio for the video, not part of the entry."),
    ("Screen recordings", "raw/nebius, raw/mixamo/*.webm, presentation/screencaps",
     "Recordings of third-party web apps, and one that shows a live cloud account."),
    ("The reports", "reports/",
     "Working record with large media embedded. Regenerable, and not part of what was "
     "asked for."),
    ("Datasets and vendored repos", "retargeted/, vendor/, raw/bandai-namco, raw/cmu-boxing",
     "95 GB, all re-fetchable, and BONES-SEED, LAFAN1 and Bandai Namco each carry terms "
     "that forbid redistributing copies or retargets."),
    ("Training checkpoints", "logs_rl/",
     "449 MB each. The exported ONNX is what a judge needs."),
]

STEPS = [
    ("Upload the video", "The 5.9 minute cut is rendered from the hand-edited blend to "
     "<code>presentation/renders/ghost_trial_03_get_over_here.mp4</code> &mdash; "
     "1920&times;1080, 30 fps, H.264 with the soundtrack in AAC. Watch it once end to end, "
     "then put it on YouTube; unlisted is enough unless the form says otherwise."),
    ("Publish the policy on Hugging Face &mdash; done", "The form wants a Hugging Face "
     "link rather "
     "than a file, so the ONNX goes up as a model repo. The card is already written &mdash; "
     "<code>policy/README.md</code> in the public tree is what Hugging Face renders as the "
     "model page. The token installed here (<code>~/.cache/huggingface/token</code>, account "
     "<code>DaveRc</code>) already carries <code>repo.write</code>, so no new token is needed:"
     "<pre>cd ~/RC/competitions/GhostTrial\n"
     ".venv/bin/hf repo create DaveRc/ghosttrial-g1-scorpion --repo-type model\n"
     ".venv/bin/hf upload DaveRc/ghosttrial-g1-scorpion \\\n"
     "  ../GhostTrial-public/policy . --repo-type model</pre>"
     "149 MB over three .onnx files, plus the card and both configs. The link to paste is "
     "<code>https://huggingface.co/DaveRc/ghosttrial-g1-scorpion</code> &mdash; the repo "
     "root, not a <code>/settings</code> or <code>/commit</code> page."),
    ("Publish the motion data as a Hugging Face dataset", "The form has a second "
     "Hugging Face field, for the dataset, and it wants a <code>dataset</code> repo &mdash; "
     "the model repo does not count for it. The card is written: "
     "<code>docs/dataset_card.md</code>, which goes up as the dataset's README."
     "<pre>cd ~/RC/competitions/GhostTrial\n"
     ".venv/bin/hf repo create DaveRc/ghosttrial-g1-scorpion-motion --repo-type dataset\n"
     ".venv/bin/hf upload DaveRc/ghosttrial-g1-scorpion-motion \\\n"
     "  docs/dataset_card.md README.md --repo-type dataset\n"
     ".venv/bin/hf upload DaveRc/ghosttrial-g1-scorpion-motion \\\n"
     "  ../GhostTrial-public/data data --repo-type dataset</pre>"
     "117 MB: the motion_lib pickles, the G1 CSV takes, the performer's BVH and the pose "
     "solves. The link to paste is "
     "<code>https://huggingface.co/datasets/DaveRc/ghosttrial-g1-scorpion-motion</code> "
     "&mdash; note the <code>/datasets/</code> in it."),
    ("The GitHub repo &mdash; done", "Pushed to "
     "<a href=\"https://github.com/SpiRaiL/GhostTrial-public\">github.com/SpiRaiL/"
     "GhostTrial-public</a>, 241 files, 256 MB, branch <code>main</code>. If anything "
     "changes, rebuild and push again:"
     "<pre>python3 tools/make_public.py --commit\n"
     "cd ../GhostTrial-public &amp;&amp; git push</pre>"),
    ("Check it as a stranger would", "Open the repo logged out. "
     "<code>docs/submission.md</code> is the entry point; confirm <code>policy/</code> holds "
     "three .onnx files and a readable card, and that nothing under <code>data/</code> looks "
     "like video."),
    ("Fill the form", f'<a href="{FORM}">{FORM}</a> &mdash; three links go in: the GitHub '
     "repo, the Hugging Face model, and the video. Use the summary in "
     "<code>docs/submission.md</code> for anything asking what the move is and how it was "
     "made."),
    ("Say what is honest about it", "The policy holds 97% double support where the target "
     "asks for 58%: it prefers stability to the target's airborne frames. Better to state "
     "that than to have a judge find it."),
]

DELIVERABLES = [
    ("ONNX-exported fine-tuned policy", "ready",
     "<code>policy/model_step_003750_{g1,encoder,decoder}.onnx</code>, 149 MB, from the "
     "Nebius checkpoint. In GitHub and on Hugging Face at "
     "<code>huggingface.co/DaveRc/ghosttrial-g1-scorpion</code>."),
    ("Dataset &mdash; Hugging Face", "needs uploading",
     "The form has its own field for it, and it wants a <code>dataset</code> repo. The data "
     "is in GitHub under <code>data/</code>; the card is <code>docs/dataset_card.md</code>. "
     "Commands in step 3."),
    ("Dataset docs + methodology", "ready",
     "<code>docs/submission.md</code>, <code>docs/video_to_pose_plan.md</code>, "
     "<code>docs/upwork_capture_brief.md</code>, <code>docs/training_env.md</code>."),
    ("Reproducible training config", "ready",
     "<code>policy/config.yaml</code> is the run as trained — 4096 envs, actor LR 2e-5, "
     "seed 0, motion <code>t12</code> — with <code>docker/</code> and "
     "<code>tools/nebius_job.sh</code> around it."),
    ("Sim demo video", "needs uploading",
     "Rendered: <code>presentation/renders/ghost_trial_03_get_over_here.mp4</code>, 5.9 "
     "minutes, 1920&times;1080 H.264 + AAC. It needs watching once and putting on YouTube."),
    ("Before/after baseline comparison", "ready",
     "In the video, and stated numerically in <code>docs/submission.md</code>: the stock "
     "policy's pelvis moves 4 cm over the phrase, the fine-tune 33 cm."),
]


def main() -> int:
    kept, dropped, sizes = survey()
    by_area = {}
    for path in kept:
        area = str(Path(path).parent).split("/")[0] or "."
        by_area.setdefault(area, []).append(path)

    rows = []
    for area in sorted(by_area):
        n = len(by_area[area])
        mb = sum(sizes[p] for p in by_area[area]) / 1e6
        rows.append(f'<tr><td><code>{esc(area)}</code></td><td>{n}</td>'
                    f'<td>{mb:.1f} MB</td><td>{AREA.get(area, "")}</td></tr>')
    rows.append('<tr><td><code>policy</code></td><td>5</td><td>153.9 MB</td>'
                f'<td>{AREA["policy"]}</td></tr>')

    held = []
    for (rule, why), paths in sorted(dropped.items()):
        held.append(f'<tr><td><code>{esc(rule)}</code></td><td>{len(paths)}</td>'
                    f'<td>{esc(why)}</td></tr>')
    never = "".join(f'<tr><td>{esc(w)}</td><td><code>{esc(p)}</code></td>'
                    f'<td>{esc(r)}</td></tr>' for w, p, r in NEVER)

    pub_body = f'''
<p class="rc-summary">The working repo is <b>{du(REPO)}</b> of tree and <b>8.2 GB</b> of
history. What goes public is <b>{du(PUBLIC)}</b> in a single commit with its own history:
the pipeline, the motion data, and the policy. Nothing is rewritten or squashed out of the
old history — the two trees are simply separate, so nothing held back can be recovered
from what is pushed.</p>

<details class="chap" open id="ch-in"><summary><span class="chnum">1</span>
<span class="chttl">What is published</span></summary>
<table><tr><th>area</th><th>files</th><th>size</th><th>what it is</th></tr>
{"".join(rows)}</table>
<p>Built by <code>tools/make_public.py</code>, which starts from
<code>git ls-files</code> — so anything already gitignored cannot leak through by
accident — subtracts the rules below, and adds the exported policy.</p>
</details>

<details class="chap" open id="ch-out"><summary><span class="chnum">2</span>
<span class="chttl">Tracked here, held back there</span></summary>
<table><tr><th>rule</th><th>files</th><th>why</th></tr>{"".join(held)}</table>
</details>

<details class="chap" open id="ch-never"><summary><span class="chnum">3</span>
<span class="chttl">Never in git at all</span></summary>
<p>These were kept out of version control from the start, so they are absent from both
trees and from the history behind them. They stay on disk and in the nightly restic
backup of <code>~/RC</code>.</p>
<table><tr><th>what</th><th>where it lives</th><th>why</th></tr>{never}</table>
</details>

<details class="chap" open id="ch-check"><summary><span class="chnum">4</span>
<span class="chttl">What was checked before publishing</span></summary>
<ul>
<li><b>No media of any kind.</b> The public tree contains no .mp4, .mov, .webm, .mp3,
.jpg, .png, .blend or .fbx — checked by extension across every file.</li>
<li><b>No secrets.</b> The Nebius scripts read <code>NB_KEY_ID</code>,
<code>NB_KEY_SECRET</code> and <code>NB_BUCKET</code> from the environment; no value
appears in any file.</li>
<li><b>History.</b> The old history was searched for the footage paths: only the Mixamo
FBX and BVH were ever committed, and those are excluded from the public tree. The MK and
capture video were never tracked.</li>
<li><b>One personal detail stays.</b> <code>README.md</code> names the Hugging Face
account and email used to accept the BONES-SEED licence. Your git commits carry the same
address; say the word and it comes out.</li>
<li><b>The performer.</b> No name, no footage, no frame. What is published is the motion:
keypoint arrays, BVH, retargeted CSV and the motion_lib pickles.</li>
</ul>
</details>
'''

    steps = "".join(
        f'<tr><td>{i}</td><td><b>{esc(t)}</b></td><td>{b}</td></tr>'
        for i, (t, b) in enumerate(STEPS, 1))
    dels = "".join(
        f'<tr><td>{esc(t)}</td>'
        f'<td class="{ "ok" if s == "ready" else "wa" }">{esc(s)}</td><td>{b}</td></tr>'
        for t, s, b in DELIVERABLES)

    sub_body = f'''
<p class="rc-summary">Deadline <b>{DEADLINE}</b>, hard. Four of the five deliverables are
done and sitting in a repo that has not been pushed anywhere yet; the fifth is the video,
which needs baking and uploading. Form:
<a href="{FORM}">account.ultimatebots.com/ghost-trial</a>.</p>

<details class="chap" open id="ch-deliv"><summary><span class="chnum">1</span>
<span class="chttl">The five deliverables</span></summary>
<table><tr><th>asked for</th><th>state</th><th>where</th></tr>{dels}</table>
</details>

<details class="chap" open id="ch-steps"><summary><span class="chnum">2</span>
<span class="chttl">The order to do it in</span></summary>
<table><tr><th>#</th><th>step</th><th>how</th></tr>{steps}</table>
</details>

<details class="chap" open id="ch-entry"><summary><span class="chnum">3</span>
<span class="chttl">What the entry claims</span></summary>
<p><b>Track:</b> Martial Arts. <b>Move:</b> the Scorpion spear throw into an uppercut, as
one continuous phrase — the transition is the part a single-pose clip cannot teach,
and "throws" is named in the track description.</p>
<p><b>Data:</b> a movement phrase commissioned and filmed for this project, lifted from
monocular video, retargeted to the G1 and hand-corrected across eleven revisions. "Lift
motion from video" and "capture your own" are both sanctioned sources. The Mortal Kombat
footage is style reference and never entered training — which matters, because the
rules put the licensing burden on the entrant.</p>
<p><b>Result:</b> the stock SONIC policy cannot crouch this move at all — 4 cm of
pelvis travel against the fine-tune's 33 cm. The fine-tune performs the phrase under full
physics, and prefers stability to the target's airborne frames.</p>
</details>

<details class="chap" open id="ch-risk"><summary><span class="chnum">4</span>
<span class="chttl">Where it is weak</span></summary>
<ul>
<li><b>Tracking, not perfection.</b> 97% double support against the target's 58%: the
policy plants where the reference leaves the floor. Stated plainly in
<code>docs/submission.md</code>.</li>
<li><b>The fundamentals check.</b> WBT-Bench scores walking and turning. The fine-tune was
trained on one phrase with control takes alongside it (<code>ctrl</code>,
<code>ctrl2</code>, <code>b1</code>), but no separate walking evaluation was run against
the final checkpoint. If there is time before the deadline, that is the one number worth
adding.</li>
<li><b>No robot.</b> Simulation only, which the rules allow.</li>
</ul>
</details>
'''

    (REPORTS / "publication.html").write_text(page(
        "publication.html", "What is published, and what is held back",
        "Everything that goes to GitHub for the submission, everything that stays on this "
        "machine, and the reason for each.", pub_body))
    (REPORTS / "submission.html").write_text(page(
        "submission.html", "Submitting Ghost Trial 03",
        "The checklist for the day: what is ready, what is left, and the order to do it "
        "in.", sub_body))
    print(f"{REPORTS / 'publication.html'}  ({len(kept)} published, "
          f"{sum(len(v) for v in dropped.values())} held back)")
    print(f"{REPORTS / 'submission.html'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
